### ISSUE TITLE
AWS Account ID

### ISSUE THREAD

**Issue by john-auld** [ned1313/Deep-Dive-Terraform#2]
FYI - The AWS account ID can be enumerated automatically, provided that the user/role employed by terraform has read permissions for sts:GetCallerIdentity.

```
data "aws_caller_identity" "current" {}

output "account_id" {
  value = "${data.aws_caller_identity.current.account_id}"
}
```

**Comment by harish417** [comment]
Initializing the backend...
bucket
  The name of the S3 bucket

  Enter a value: dummybuck


Error configuring the backend "s3": No valid credential sources found for AWS Provider.
        Please see https://terraform.io/docs/providers/aws/index.html for more information on
        providing credentials for the AWS Provider

Please update the configuration in your Terraform files to fix this error
then run this command again.


##################
1. i am facing this error when running init
2. i need the state file that is in bucket but i  dont have any bucket objects so please clarify my doubts


Thanks,
HARISH NAIDU K

**Comment by ned1313** [comment]
Harish,
In order to initialize the s3 backend, you need to provide valid AWS credentials that can write to the bucket.  The credentials can be passed as arguments when running the terraform initialization process:

`terraform init -backend-config="access_key=XXXXXXX" -backend-config="secret_key=XXXXXXXX"`

If you don't specify credential, then Terraform will also look in your user directory for the file ~/.aws/credentials and use the default credential if there is one specified.  

Terraform will also check the environment variables AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY for values.

If all of those fail, then you will receive an error that Terraform has no valid credentials to access the bucket.

The full doc for the s3 backend is [here](https://www.terraform.io/docs/backends/types/s3.html).  I would also recommend reading the doc on [partial configs](https://www.terraform.io/docs/backends/config.html).

**Comment by harish417** [comment]
i passed keys it is working fot init

but for plan it is saying that access denied

**Comment by ned1313** [comment]
This deals with the previous version of the course, and I am going to go ahead and close the issue.
